name = "Unnamed Progression Pack"
author = "TrueCP5"
version = "0.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c3cd46ab8ee0d7febb236e60cffe125f2423703c57ea3ea1410df27b3e705d42"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
