name = "Unnamed Progression Pack"
author = "TrueCP5"
version = "0.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bf4bb408fd94000826d549a08cfe32d90fb520bb686dc7b694122806f0057a44"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
