name = "Unnamed Progression Pack"
author = "TrueCP5"
version = "0.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3e6a9f3ff8186abbcfc680229302f82e3fc2eb4210cc1a68b9bfcbbc709e9d66"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
