name = "Unnamed Progression Pack"
author = "TrueCP5"
version = "0.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f6b7f78525889d51d65d5cb44529f8ca64da1c4888f00ced680e38739a97f49d"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
