name = "Unnamed Progression Pack"
author = "TrueCP5"
version = "0.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b7bcbb95c98795c072b92aeb8f62771cc4d9d75b804169b49abbae2688428d8f"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
