name = "Unnamed Progression Pack"
author = "TrueCP5"
version = "0.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ca60eba9f4ded01851318a905343e2e770f8e690af029cc52b30e43b6a3460ea"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"

[export]
[export.curseforge]
disable-jumploader = false
jumploader-forge-version = "36.1.18"
jumploader-version-id = 3227191
project-id = 0
