name = "Unnamed Progression Pack"
author = "TrueCP5"
version = "0.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "caacb2260e18ae1641994266e03844f7fee85408a8ccd06a55c77b0f05ae2e49"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
