name = "Advancements Debug"
filename = "advdebug-2.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3122/49/advdebug-2.2.0.jar"
hash-format = "murmur2"
hash = "106005204"

[update]
[update.curseforge]
file-id = 3122049
project-id = 422316
release-channel = "beta"
