name = "Architectury API (Fabric)"
filename = "architectury-1.10.142-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3274/711/architectury-1.10.142-fabric.jar"
hash-format = "murmur2"
hash = "1651957831"

[update]
[update.curseforge]
file-id = 3274711
project-id = 419697
release-channel = "beta"
