name = "Architectury API (Fabric)"
filename = "architectury-1.14.157-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3312/990/architectury-1.14.157-fabric.jar"
hash-format = "murmur2"
hash = "559274333"

[update]
[update.curseforge]
file-id = 3312990
project-id = 419697
release-channel = "beta"
