name = "Architectury API (Fabric)"
filename = "architectury-1.17.18-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3330/396/architectury-1.17.18-fabric.jar"
hash-format = "murmur2"
hash = "532972495"

[update]
[update.curseforge]
file-id = 3330396
project-id = 419697
release-channel = "beta"
