name = "Bewitchment"
filename = "bewitchment-1.16.5-14.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3313/201/bewitchment-1.16.5-14.jar"
hash-format = "murmur2"
hash = "630040803"

[update]
[update.curseforge]
file-id = 3313201
project-id = 394915
release-channel = "beta"
