name = "Cardinal Components"
filename = "Cardinal-Components-API-2.8.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3312/678/Cardinal-Components-API-2.8.3.jar"
hash-format = "murmur2"
hash = "4074895419"

[update]
[update.curseforge]
file-id = 3312678
project-id = 318449
release-channel = "beta"
