name = "Cardinal Components"
filename = "Cardinal-Components-API-2.8.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3295/352/Cardinal-Components-API-2.8.1.jar"
hash-format = "murmur2"
hash = "2904504997"

[update]
[update.curseforge]
file-id = 3295352
project-id = 318449
release-channel = "beta"
