name = "FTB Teams (Fabric)"
filename = "ftb-teams-fabric-1605.2.1-build.8.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3329/975/ftb-teams-fabric-1605.2.1-build.8.jar"
hash-format = "murmur2"
hash = "1318782151"

[update]
[update.curseforge]
file-id = 3329975
project-id = 438497
release-channel = "beta"
