name = "FTB Quests (Fabric)"
filename = "ftb-quests-1605.2.1-build.39-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3249/259/ftb-quests-1605.2.1-build.39-fabric.jar"
hash-format = "murmur2"
hash = "3547901662"

[update]
[update.curseforge]
file-id = 3249259
project-id = 438496
release-channel = "beta"
