name = "FTB Teams (Fabric)"
filename = "ftb-teams-1604.1.0.16-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3237/173/ftb-teams-1604.1.0.16-fabric.jar"
hash-format = "murmur2"
hash = "582706390"

[update]
[update.curseforge]
file-id = 3237173
project-id = 438497
release-channel = "beta"
