name = "FTB Library (Fabric)"
filename = "ftb-library-1605.3.0-build.67-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3313/35/ftb-library-1605.3.0-build.67-fabric.jar"
hash-format = "murmur2"
hash = "3826152211"

[update]
[update.curseforge]
file-id = 3313035
project-id = 438495
release-channel = "beta"
