name = "GeckoLib [FABRIC]"
filename = "geckolib-fabric-1.16.5-3.0.30.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3275/570/geckolib-fabric-1.16.5-3.0.30.jar"
hash-format = "murmur2"
hash = "4200546540"

[update]
[update.curseforge]
file-id = 3275570
project-id = 398667
release-channel = "beta"
