name = "GeckoLib [FABRIC]"
filename = "geckolib-fabric-1.16.5-3.0.33.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3295/308/geckolib-fabric-1.16.5-3.0.33.jar"
hash-format = "murmur2"
hash = "444063086"

[update]
[update.curseforge]
file-id = 3295308
project-id = 398667
release-channel = "beta"
