name = "Impersonate"
filename = "Impersonate-2.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3296/423/Impersonate-2.2.0.jar"
hash-format = "murmur2"
hash = "3214838135"

[update]
[update.curseforge]
file-id = 3296423
project-id = 360333
release-channel = "beta"
