name = "Krypton"
filename = "krypton-0.1.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3200/819/krypton-0.1.2.jar"
hash-format = "murmur2"
hash = "1855572908"

[update]
[update.curseforge]
file-id = 3200819
project-id = 428912
release-channel = "beta"
