name = "KubeJS (Fabric)"
filename = "kubejs-1605.3.7-build.196-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3309/391/kubejs-1605.3.7-build.196-fabric.jar"
hash-format = "murmur2"
hash = "3772922652"

[update]
[update.curseforge]
file-id = 3309391
project-id = 395864
release-channel = "beta"
