name = "KubeJS Fabric"
filename = "kubejs-1605.3.7-build.184-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3281/406/kubejs-1605.3.7-build.184-fabric.jar"
hash-format = "murmur2"
hash = "285622270"

[update]
[update.curseforge]
file-id = 3281406
project-id = 395864
release-channel = "beta"
