name = "Miskatonic Mysteries"
filename = "miskatonicmysteries-0.0.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3309/519/miskatonicmysteries-0.0.5.jar"
hash-format = "murmur2"
hash = "1178873867"

[update]
[update.curseforge]
file-id = 3309519
project-id = 473458
release-channel = "beta"
