name = "Modern Industrialization"
filename = "Modern-Industrialization-0.4.0-alpha.03.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3311/463/Modern-Industrialization-0.4.0-alpha.03.jar"
hash-format = "murmur2"
hash = "3214477644"

[update]
[update.curseforge]
file-id = 3311463
project-id = 405388
release-channel = "beta"
