name = "Modern Industrialization"
filename = "Modern-Industrialization-0.3.16.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3274/195/Modern-Industrialization-0.3.16.jar"
hash-format = "murmur2"
hash = "1800174506"

[update]
[update.curseforge]
file-id = 3274195
project-id = 405388
release-channel = "beta"
