name = "Modern Industrialization"
filename = "Modern-Industrialization-0.4.0-alpha.06.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3325/906/Modern-Industrialization-0.4.0-alpha.06.jar"
hash-format = "murmur2"
hash = "3260530828"

[update]
[update.curseforge]
file-id = 3325906
project-id = 405388
release-channel = "beta"
