name = "Sandwichable"
filename = "sandwichable-1.2-beta5--1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3206/686/sandwichable-1.2-beta5--1.16.5.jar"
hash-format = "murmur2"
hash = "3275593468"

[update]
[update.curseforge]
file-id = 3206686
project-id = 374143
release-channel = "beta"
