name = "WTHIT"
filename = "wthit-2.10.2-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3330/281/wthit-2.10.2-fabric.jar"
hash-format = "murmur2"
hash = "663650953"

[update]
[update.curseforge]
file-id = 3330281
project-id = 440979
release-channel = "beta"
