name = "WTHIT"
filename = "wthit-2.7.0-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3274/367/wthit-2.7.0-fabric.jar"
hash-format = "murmur2"
hash = "581337585"

[update]
[update.curseforge]
file-id = 3274367
project-id = 440979
release-channel = "beta"
