name = "WTHIT"
filename = "wthit-2.7.1-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3289/379/wthit-2.7.1-fabric.jar"
hash-format = "murmur2"
hash = "1465934729"

[update]
[update.curseforge]
file-id = 3289379
project-id = 440979
release-channel = "beta"
