name = "Xaero's Minimap"
filename = "Xaeros_Minimap_21.8.2_Fabric_1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3316/359/Xaeros_Minimap_21.8.2_Fabric_1.16.5.jar"
hash-format = "murmur2"
hash = "305712914"

[update]
[update.curseforge]
file-id = 3316359
project-id = 263420
release-channel = "beta"
